### ISSUE TITLE
Cannot "git clone --recursive" submodule HeteroArenaAllocator

### ISSUE THREAD

**Issue by CodeTalker625** [Therdel/cssHack#4]
if you take a look at "lib/BoyerMoore-DontCare/.gitmodules", you'll notice that the "url" for the "HeteroArenaAllocator" submodule is not using https. Therefore, when doing "git clone --recursive" to download the cssHack project, permission will be denied when it gets to that submodule. To fix it, simply update the "url" to point to "https://github.com/Therdel/HeteroArenaAllocator.git" instead of "git@github.com:Therdel/HeteroArenaAllocator.git". 

A workaround is to manually clone that submodule after cloning the cssHack project.

**Comment by Therdel** [comment]
Thanks for taking the time. I tested it, it previously only worked when cloning with ssh, but not with https.
I pushed the fix on master.

Next time, you can create a pull request
