### ISSUE TITLE
what are the dependency packages required?

### ISSUE THREAD

**Issue by liberteryen** [Therdel/cssHack#5]
![resim](https://user-images.githubusercontent.com/84645312/189413759-470e742d-ac68-459d-92f1-ab7483e782aa.png)
It was said in the previous location that 32bit is required. I also created a virtual 32bit debian and got such an error in compiling. Which dependency did I not install?

**Comment by Therdel** [comment]
`std::numeric_limits` is part of the c++ STL, not a dependency.
Try it with a `#include <limits>` in BadCharTable.cpp
